Reproduction Attempt: Bug Fixes and Improvements Commit Series 13
Update README.md: Installation Guidelines
1. Added change to correct directory for installation

2. While running installation guideline for raw37 and py37, encountered this error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flake8 4.0.1 requires importlib-metadata<4.3; python_version < "3.8", but you have importlib-metadata 6.0.0 which is incompatible.
flake8 4.0.1 requires mccabe<0.7.0,>=0.6.0, but you have mccabe 0.7.0 which is incompatible.

This is discussed in a github issue: https://github.com/pypa/pipenv/issues/4476

Added Fix : use command:
pip install -U pipenv